<a href="https://colab.research.google.com/github/Raman369AI/Agents/blob/master/practice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Stacks: Data is stored in the same order which they arrive, ordered list with insertion and deletion done on the top. LIFO/ FILO. PUSH and POP.
Empty stack POP - Underflow.
Push into Full stack - Overflow.

In [ ]:
class Stack:
  def __init__(self, n):
    self.hold = []*n
    self.limit = n

  def push(self, value):
    if len(self.hold) < self.limit:
      self.hold.append(value)
    else:
      raise OverflowError('Stack is full')
      return self.hold

  def pop(self):
    if len(self.hold) == 0:
      raise ValueError('Stack is empty')

    return self.hold.pop()

  def top(self):
    if len(self.hold) == 0:
      raise ValueError('Stack is empty')
    return self.hold[-1]

  def size(self):
    return len(self.hold)

  def isEmpty(self):
    return self.hold == []

  def fullStack(self):
    return len(self.hold) == self.limit

  def __repr__(self):
    return f'The list is {self.hold}'




In [ ]:
r = Stack(5)

In [ ]:
r.push(3)

In [ ]:
print(r)

The list is [3, 3]


In [ ]:
r.pop()

3

In [ ]:
r

The list is []

In [ ]:
r.top()

ValueError: Stack is empty

In [ ]:
def palindrome(s : str) -> bool:
  return s == s[::-1]


In [ ]:
palindrome('Raman')

False

In [ ]:
def valid_string(s:str):
  stack = Stack(len(s))
  for i in s:
    if i in '([{':
      stack.push(i)

    elif i in ')]}':
      p = stack.pop()
      if p == '(' and i == ')':
        continue
      elif p == '[' and i == ']':
        continue
      elif p == '{' and i == '}':
        continue
      else:
        return False
    else:
      return 'Not a string'


In [ ]:
valid_string('()')

True

Queue: FIFO or LILO, ordered in insertion.

In [ ]:
tail =  4
el = 5
tail = (tail+1)%el
tail

0

In [ ]:
class myQueue:
  def __init__(self, size):
    self.size =  size
    self.queue = [None]*size
    self.head = 0
    self.tail = 0
    self.count = 0

  def enqueue(self, value):
    if self.count < self.size:
      self.queue[self.tail] = value
      self.tail = (self.tail + 1) % self.size
      self.count += 1
    else:
      raise OverflowError('Queue is full')

  def dequeue(self):
    if len(self.queue) == 0:
      raise ValueError('Queue is empty')
    item = self.queue[self.head]
    self.queue[self.head] = None
    self.head = (self.head + 1) % self.size
    self.count -= 1

    return item

  def isEmpty(self):
    return self.queue == []

  def __repr__(self):
    return f'The queue is {self.queue}'


In [ ]:
q = myQueue(5)

In [ ]:
q

The queue is [None, None, None, None, None]

In [ ]:
q.enqueue(2)

In [ ]:
q

The queue is [2, None, None, None, None]

Insertion Sort: Sub problems, 1 value is always sorted -
2, 3 elements sorted and so on.

In [ ]:
def insertion_sort(l):
  '''The input is a unsorted list and the output is a sorted list / array like structure
  1. The first element is sorted
  2. The first two,
  3. The first 3 etc:
  Check the empty list:
  compare the first and last elements else loop through the entire r list
  '''
  if not l:
    return []
  r = []
  r.append(l[0])
  for j in range(1,len(l)):
    key = l[j]
    if key >= r[-1]:
        r.append(key)
        continue
    else:
      for i in range(len(r)):

        if key < r[i]:
          r.insert(i, key)
          break
  return r



In [ ]:
insertion_sort([1,2,5,3,5])

[3, 5, 5, 5, 5]

In [ ]:
def insertion_sort(l):
  '''The input is a unsorted list and the output is a sorted list / array like structure
  1. The first element is sorted
  2. The first two,
  3. The first 3 etc:
  Check the empty list:
  compare the first and last elements else loop through the entire r list
  '''
  if not l:
    return []
  for i in range(1,len(l)):
    key = l[i]
    if i > 0:
      for j in range(i):
        if key < l[j]:
          l.insert(j, key)
          l.pop(i+1)
          break
      else:
        continue
  return l




Compare with the last item - if greater keep it there else iterate and shift. O(n) - Best Case but Worst case O(n2), It is an inplace sorting - No additional datastructures are to be used. Space Complexity is O(1)

In [ ]:
from typing import List
def insertion_sort(l:List) -> List:
  '''Args: l - Dynamic array/ list
  result - List sorted in ascending order
  '''
  if not l:
    return []
  # If the while condition is
  # satisfied simply shift else keep it in the same place.

  for i in range(1,len(l)):
    key = l[i]
    j = i - 1
    while j >= 0 and key < l[j]:
      l[j+1] = l[j]
      j -= 1
    l[j + 1] = key
  return l



In [ ]:
merge_sort([1,2,5,3,5])

[1, 2, 3, 5, 5]

Stable and Unstable sort: Stable sort will preserve the order when it is a tie. Else it is unstable sorting it might or might not.

Action,Python Code,"What happens to ""Pointers"""
Capture,key = l[i],key now points to the object at l[i].
Shift,l[j+1] = l[j],Index j+1 updates its pointer to match index j.
Insert,l[j+1] = key,"The ""hole"" at j+1 is told to point to the key object."

Merge sort is nlogn , n for merge and logn is due to the levels.

In [ ]:
def merge_sort(l:List):
  '''Input is a list and the output is a sorted version of the list.'''
  if len(l) <= 1:
    return l

  l1 = merge_sort(l[:len(l)//2])
  l2 = merge_sort(l[len(l)//2:])
  return merge(l1,l2)

def merge(l1:List, l2:List):
  '''O(n) operation'''
  result = []
  i = j = 0
  while i < len(l1) and j < len(l2):
    if l1[i] < l2[j]:
      result.append(l1[i])
      i += 1
    else:
      result.append(l2[j])
      j += 1
  result.extend(l1[i:])
  result.extend(l2[j:])
  return result





[1,3,2,4,5,2]

In [ ]:
from typing import List

In [ ]:
def quick_sort(l, s, e):
  '''This is not usual - it involves swapping and inplace too nlogn'''
  if s >= e:
    return l
  left = s
  for i in range(s,e):
    if l[i] < l[e]:
      l[left],l[i] = l[i], l[left]
      left += 1
  l[left],l[e] = l[e],l[left]
  quick_sort(l,s,left-1)
  quick_sort(l,left+1,e)
  return l

In [ ]:
def counting_sort(l):
  m = max(l)
  tmp = [0]*(m+1)
  for i in l:
    tmp[i] += 1
  for i in range(1,len(tmp)):
    tmp[i] = tmp[i] + tmp[i-1]
  result = [0]*len(l)
  for i in range(len(l)-1, -1, -1):
    val = l[i]
    position = tmp[val]
    result[position - 1] = val
    tmp[val] -= 1
  return result

In [ ]:
counting_sort([1,2,2,3,3,3,4,8])

[1, 2, 2, 3, 3, 3, 4, 8]

In [ ]:
for i in range(len([1,2,2,3,3,3,4,8])-1, -1, -1):
  print(i)

7
6
5
4
3
2
1
0


In [ ]:
def binary_search(l, item, left,right):
  '''Assume the list is sorted'''
  if left > right:
    return -1
  guess = (left + right)//2
  center = l[guess]
  if center > item:
    return binary_search(l, item,left,guess-1)
  if center < item:
    return binary_search(l, item, guess+1, right)
  else:
    return guess


In [ ]:
binary_search([1,2,3,4,6,7,8],8)

6

In [ ]:
def binary_search(l,item):

  '''Efficient method of binary search -
  use two pointers to play with the list
  manipulate in place 0log(n)'''
  left = 0
  right = len(l) - 1
  while left <= right:
    mid = (left+right)//2
    if item > l[mid]:
      left = mid + 1
    elif item <l[mid]:
      right = mid - 1
    else:
      return mid
  return -1

In [ ]:
'''We can't have cycles in a Binary Tree
Root Node:
Leaf Node:
Parent Node:
Child Node:
Sibling Nodes
All nodes must be connected to the tree.

Properties:
Height: A single node has height of 1,
From the given node to the lowest descendent of the node under consideration -
provided the longest path is obtained.
For root node every node is a descendent.
The sub tree's themselves must be binary search trees
Depth:  Path from the lowest descendent to the root node.

Binary Search Tree's do not strictly contain duplicates
'''

In [ ]:
'''
1. Tree is a non-linear data structure
2. Ordering is not needed.
3. Binary tree is when each node has 0 or 1 or 2 child.
Strict Binary Tree - Each node either 2 or 0 child
Full Binary tree - All nodes each two nodes each.
Complete Binary tree - If all leaf nodes are at height / height -1

Structure - Data , left and right pointer.

Operations: Insertion, deletion, search , traversing, height and depth
'''

In [ ]:
class Node:
  def __init__(self, value):
    self.value = value
    self.left = None
    self.right = None

In [ ]:
class binary_search_tree:

  def __init__(self):
    self.root = None

  def insert(self,value,root):
    if self.root is None:
      self.root = Node(value)
      return
    else:
      if value < self.root.value:
        self.insert(value,root.left)
      else:
        self.insert(value,root.right)

In [ ]:
# BReadth First Search -  Doesn't suit recursion:
'''Move left to right - Root,left, right
Save the pointer to go to the left - Recursion is not suited.
Process the children of the left and right.
'''

from collections import deque

def bfs(root)

In [1]:
import numpy as np


In [3]:
a = np.array([[1,1,6],[1,3,1],[1,1,4]])

In [4]:
a

array([[1, 1, 6],
       [1, 3, 1],
       [1, 1, 4]])

In [1]:
import torch

# Create a 3x3 matrix on the GPU (if available)
device = "cuda" if torch.cuda.is_available() else "cpu"
A = torch.tensor([[1., 2., 3.], [2., 5., 8.], [3., 8., 14.]], device=device)

# 1. lu_factor: Returns a compact LU and the pivot indices (best for solving)
LU_data, pivots = torch.linalg.lu_factor(A)

# 2. lu: Returns the explicit P, L, and U matrices (best for inspection)
P, L, U = torch.linalg.lu(A)

print(f"L matrix:\n{L}")
print(f"U matrix:\n{U}")

L matrix:
tensor([[1.0000, 0.0000, 0.0000],
        [0.3333, 1.0000, 0.0000],
        [0.6667, 0.5000, 1.0000]])
U matrix:
tensor([[ 3.0000,  8.0000, 14.0000],
        [ 0.0000, -0.6667, -1.6667],
        [ 0.0000,  0.0000, -0.5000]])


In [2]:
torch.linalg.lu(A)

torch.return_types.linalg_lu(
P=tensor([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]),
L=tensor([[1.0000, 0.0000, 0.0000],
        [0.3333, 1.0000, 0.0000],
        [0.6667, 0.5000, 1.0000]]),
U=tensor([[ 3.0000,  8.0000, 14.0000],
        [ 0.0000, -0.6667, -1.6667],
        [ 0.0000,  0.0000, -0.5000]]))